apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  labels:
    app: vpromq
spec:
  selector:
    matchLabels:
      app: vpromq
  replicas: 1
  template:
    metadata:
      labels:
        app: vpromq
    spec:
      containers:
      - name: vpromq01
        image: rabbitmq
        ports:
        - name: vpromq-port
          containerPort: 5672
        env: 
         - name: RABBITMQ_DEFAULT_PASS
           valueFrom:
             secretKeyRef:
               name: my-secret
               key: rmq-password
         - name: RABBITMQ_DEFAULT_USER
           value: "guest"