apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  dbpasss: dnByb2RicGFzcw==  # base64 encoded value of 'vprodbpass'
  rmq-pass: Z3Vlc3Q=  # base64 encoded value of 'guest'

